# 01 - Limpeza e Tratamentos dos dados

## Primeiros passos

In [ ]:
#Importa bibliotecas utilizadas
import pandas as pd
import numpy as np
import json

In [ ]:
#Abre o arquivo
with open('.../Dados/Telco-Customer-Churn.json') as file:
  data = json.load(file)

In [ ]:
#Mostra o arquivo normalizado
df = pd.json_normalize(data)
df

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

## Verificando se existem valores nulos

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

Pode-se observar que não há valores nulos em nenhuma coluna do Data Frame

## Outras Verificações:

O próximo passo é analisar cada uma das colunas individualmente com o objetivo de:
+ Verificar se existem valores em branco 
+ Verificar se respostas correspondem com respectivas colunas

In [ ]:
df.isna().sum()

customerID                   0
Churn                        0
customer.gender              0
customer.SeniorCitizen       0
customer.Partner             0
customer.Dependents          0
customer.tenure              0
phone.PhoneService           0
phone.MultipleLines          0
internet.InternetService     0
internet.OnlineSecurity      0
internet.OnlineBackup        0
internet.DeviceProtection    0
internet.TechSupport         0
internet.StreamingTV         0
internet.StreamingMovies     0
account.Contract             0
account.PaperlessBilling     0
account.PaymentMethod        0
account.Charges.Monthly      0
account.Charges.Total        0
dtype: int64

Percebe-se que não há valores em branco, aparentemente.

In [ ]:
#Imprime valores contidos em cada coluna
for coluna in df.columns:
    print(df[coluna].value_counts())

0002-ORFBO    1
6614-VBEGU    1
6637-KYRCV    1
6635-MYYYZ    1
6635-CPNUN    1
             ..
3374-TTZTK    1
3374-PZLXD    1
3374-LXDEV    1
3373-YZZYM    1
9995-HOTOH    1
Name: customerID, Length: 7267, dtype: int64
No     5174
Yes    1869
        224
Name: Churn, dtype: int64
Male      3675
Female    3592
Name: customer.gender, dtype: int64
0    6085
1    1182
Name: customer.SeniorCitizen, dtype: int64
No     3749
Yes    3518
Name: customer.Partner, dtype: int64
No     5086
Yes    2181
Name: customer.Dependents, dtype: int64
1     634
72    369
2     246
3     207
4     185
     ...
38     60
39     59
44     54
36     50
0      11
Name: customer.tenure, Length: 73, dtype: int64
Yes    6560
No      707
Name: phone.PhoneService, dtype: int64
No                  3495
Yes                 3065
No phone service     707
Name: phone.MultipleLines, dtype: int64
Fiber optic    3198
DSL            2488
No             1581
Name: internet.InternetService, dtype: int64
No                     3608
Yes                    2078
No internet service    1581
Name: internet.OnlineSecurity, dtype: int64
No                     3182
Yes                    2504
No internet service    1581
Name: internet.OnlineBackup, dtype: int64
No                     3195
Yes                    2491
No internet service    1581
Name: internet.DeviceProtection, dtype: int64
No                     3582
Yes                    2104
No internet service    1581
Name: internet.TechSupport, dtype: int64
No                     2896
Yes                    2790
No internet service    1581
Name: internet.StreamingTV, dtype: int64
No                     2870
Yes                    2816
No internet service    1581
Name: internet.StreamingMovies, dtype: int64
Month-to-month    4005
Two year          1743
One year          1519
Name: account.Contract, dtype: int64
Yes    4311
No     2956
Name: account.PaperlessBilling, dtype: int64
Electronic check             2445
Mailed check                 1665
Bank transfer (automatic)    1589
Credit card (automatic)      1568
Name: account.PaymentMethod, dtype: int64
20.05     65
19.85     46
19.90     46
19.70     45
19.55     45
          ..
23.45      1
116.55     1
106.85     1
68.55      1
67.85      1
Name: account.Charges.Monthly, Length: 1585, dtype: int64
           11
20.2       11
19.75       9
19.55       9
19.9        9
           ..
272         1
1426.45     1
371.6       1
6786.4      1
3707.6      1
Name: account.Charges.Total, Length: 6531, dtype: int64

Com o método .value_counts() percebe-se que as os valores estão adequados ao que representa cada coluna do DataFrame, porém a coluna "Chur"apresenta valores em branco.

In [ ]:
df.Churn.unique()

array(['No', 'Yes', ''], dtype=object)

In [ ]:
#Seleciona as linhas com Churn em branco
df.query("Churn == ''")

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
30,0047-ZHDTW,,Female,0,No,No,11,Yes,Yes,Fiber optic,...,No,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),79.00,929.3
75,0120-YZLQA,,Male,0,No,No,71,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card (automatic),19.90,1355.1
96,0154-QYHJU,,Male,0,No,No,29,Yes,No,DSL,...,Yes,No,Yes,No,No,One year,Yes,Electronic check,58.75,1696.2
98,0162-RZGMZ,,Female,1,No,No,5,Yes,No,DSL,...,Yes,No,Yes,No,No,Month-to-month,No,Credit card (automatic),59.90,287.85
175,0274-VVQOQ,,Male,1,Yes,No,65,Yes,Yes,Fiber optic,...,Yes,Yes,No,Yes,Yes,One year,Yes,Bank transfer (automatic),103.15,6792.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7158,9840-GSRFX,,Female,0,No,No,14,Yes,Yes,DSL,...,Yes,No,No,No,No,One year,Yes,Mailed check,54.25,773.2
7180,9872-RZQQB,,Female,0,Yes,No,49,No,No phone service,DSL,...,No,No,No,Yes,No,Month-to-month,No,Bank transfer (automatic),40.65,2070.75
7211,9920-GNDMB,,Male,0,No,No,9,Yes,Yes,Fiber optic,...,No,No,No,No,No,Month-to-month,Yes,Electronic check,76.25,684.85
7239,9955-RVWSC,,Female,0,Yes,Yes,67,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),19.25,1372.9
7247,9966-VYRTZ,,Female,0,Yes,Yes,31,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check,19.55,658.95

Temos a confirmação de que 224 linhas possuem valores em branco na coluna Churn. Uma vez que esta é a variável mais importante, ou seja, é a coluna que contém os resultados que queremos classificar ao final do problema, foi optado por excluir estas 224 linhas.

In [ ]:
#Cria filtro que exclui as linhas com Churn em branco 
df = df.query("Churn!= ''") 
df

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

In [ ]:
df.Churn.unique()

array(['No', 'Yes'], dtype=object)

A coluna "Charges Total" está sendo lida como typo objetc, ao invés de float. Portanto vamos transformar estes valores em numéricos

In [ ]:
df['account.Charges.Total'].unique()

array(['593.3', '542.4', '280.85', ..., '742.9', '4627.65', '3707.6'],
      dtype=object)

In [ ]:
#Transforma account.Charges.Total em valores numericos
#df["account.Charges.Total"] = pd.to_numeric(df["account.Charges.Total"])          #erro na linha 945

Aqui os valores estão sendo percebidos como "object", porém ao tentar transformar-los em valores float, encontramos um erro pois, algumas linhas possuem valores em branco na coluna "Charges Total".

In [ ]:
#Analisa os dados contidos na linha em que ocorreu erro
df.iloc[945]

customerID                                1371-DWPAZ
Churn                                             No
customer.gender                               Female
customer.SeniorCitizen                             0
customer.Partner                                 Yes
customer.Dependents                              Yes
customer.tenure                                    0
phone.PhoneService                                No
phone.MultipleLines                 No phone service
internet.InternetService                         DSL
internet.OnlineSecurity                          Yes
internet.OnlineBackup                            Yes
internet.DeviceProtection                        Yes
internet.TechSupport                             Yes
internet.StreamingTV                             Yes
internet.StreamingMovies                          No
account.Contract                            Two year
account.PaperlessBilling                          No
account.PaymentMethod        Credit card (automatic)
account.Charges.Monthly                        56.05
account.Charges.Total
Name: 975, dtype: object

In [ ]:
df.isna().sum()

customerID                   0
Churn                        0
customer.gender              0
customer.SeniorCitizen       0
customer.Partner             0
customer.Dependents          0
customer.tenure              0
phone.PhoneService           0
phone.MultipleLines          0
internet.InternetService     0
internet.OnlineSecurity      0
internet.OnlineBackup        0
internet.DeviceProtection    0
internet.TechSupport         0
internet.StreamingTV         0
internet.StreamingMovies     0
account.Contract             0
account.PaperlessBilling     0
account.PaymentMethod        0
account.Charges.Monthly      0
account.Charges.Total        0
dtype: int64

In [ ]:
#Procura por outras linhas que possuem account.Charges.Total em branco
df.loc[(df['account.Charges.Total'] == ' ')]

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
975,1371-DWPAZ,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,
1775,2520-SGTTA,No,Female,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,
1955,2775-SEFEE,No,Male,0,No,Yes,0,Yes,Yes,DSL,...,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,
2075,2923-ARZLG,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,
2232,3115-CZMZD,No,Male,0,No,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,
2308,3213-VVOLG,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,
2930,4075-WKNIU,No,Female,0,Yes,Yes,0,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,
3134,4367-NUYAO,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,
3203,4472-LVYGI,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,
4169,5709-LVOEQ,No,Female,0,Yes,Yes,0,Yes,No,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,
5599,7644-OMVMY,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,

Após alguns testes, foi possível perceber que  todas as 11 linhas que possuem "Charges.Total" em branco também possuem a coluna "customer.ternure" = 0

In [ ]:
#Procura por linhas que possuem customer.tenure em branco
df.loc[(df['customer.tenure'] == 0)]

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
975,1371-DWPAZ,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,
1775,2520-SGTTA,No,Female,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,
1955,2775-SEFEE,No,Male,0,No,Yes,0,Yes,Yes,DSL,...,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,
2075,2923-ARZLG,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,
2232,3115-CZMZD,No,Male,0,No,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,
2308,3213-VVOLG,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,
2930,4075-WKNIU,No,Female,0,Yes,Yes,0,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,
3134,4367-NUYAO,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,
3203,4472-LVYGI,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,
4169,5709-LVOEQ,No,Female,0,Yes,Yes,0,Yes,No,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,
5599,7644-OMVMY,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,

E o inverso também se mostra verdadeiro, ou seja,  todas as linhas que possuem o customer.ternure = 0 possuem Charges.Total em branco.

Entende-se, portanto, que os valores estão em branco pois os contratos duraram menos de 1 mês. Sendo assim, a proxima linha de código iguala os valores em brancos em "account.Charges.Total" aos valores da coluna "account.Charges.Monthly", que neste caso, representa o valor real cobrado.

In [ ]:
df.loc[(df['account.Charges.Total'] == ' '),'account.Charges.Total'] = df.loc[(df['account.Charges.Total'] == ' '),'account.Charges.Monthly']

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

In [ ]:
df

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7043 non-null   object
 1   Churn                      7043 non-null   object
 2   customer.gender            7043 non-null   object
 3   customer.SeniorCitizen     7043 non-null   int64
 4   customer.Partner           7043 non-null   object
 5   customer.Dependents        7043 non-null   object
 6   customer.tenure            7043 non-null   int64
 7   phone.PhoneService         7043 non-null   object
 8   phone.MultipleLines        7043 non-null   object
 9   internet.InternetService   7043 non-null   object
 10  internet.OnlineSecurity    7043 non-null   object
 11  internet.OnlineBackup      7043 non-null   object
 12  internet.DeviceProtection  7043 non-null   object
 13  internet.TechSupport       7043 non-null   object
 14  internet.StreamingTV       7043 non-null   object
 15  internet.StreamingMovies   7043 non-null   object
 16  account.Contract           7043 non-null   object
 17  account.PaperlessBilling   7043 non-null   object
 18  account.PaymentMethod      7043 non-null   object
 19  account.Charges.Monthly    7043 non-null   float64
 20  account.Charges.Total      7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

Por fim, é possível transformar a coluna 20 para o tipo *float*

In [ ]:
df["account.Charges.Total"] = pd.to_numeric(df["account.Charges.Total"])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7043 non-null   object
 1   Churn                      7043 non-null   object
 2   customer.gender            7043 non-null   object
 3   customer.SeniorCitizen     7043 non-null   int64
 4   customer.Partner           7043 non-null   object
 5   customer.Dependents        7043 non-null   object
 6   customer.tenure            7043 non-null   int64
 7   phone.PhoneService         7043 non-null   object
 8   phone.MultipleLines        7043 non-null   object
 9   internet.InternetService   7043 non-null   object
 10  internet.OnlineSecurity    7043 non-null   object
 11  internet.OnlineBackup      7043 non-null   object
 12  internet.DeviceProtection  7043 non-null   object
 13  internet.TechSupport       7043 non-null   object
 14  internet.StreamingTV       7043 non-null   object
 15  internet.StreamingMovies   7043 non-null   object
 16  account.Contract           7043 non-null   object
 17  account.PaperlessBilling   7043 non-null   object
 18  account.PaymentMethod      7043 non-null   object
 19  account.Charges.Monthly    7043 non-null   float64
 20  account.Charges.Total      7043 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [ ]:
df

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.30
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.40
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.90
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60

## Aplicando Econding nas variáveis
Agora, iremos transformas os valores *object* em valores numéricos binários. Desta forma, o processo de análise dos dados, bem como a criação do modelo de Machine Learnng serão facilitados.

Para as variáveis que possuem respostas somente "Yes" e "No", vamos apenas substituir por 1 e 0.

In [ ]:
for coluna in df.columns:
    print(df[coluna].value_counts())

0002-ORFBO    1
6616-AALSR    1
6625-UTXEW    1
6625-IUTTT    1
6625-FLENO    1
             ..
3352-RICWQ    1
3352-ALMCK    1
3351-NQLDI    1
3351-NGXYI    1
9995-HOTOH    1
Name: customerID, Length: 7043, dtype: int64
No     5174
Yes    1869
Name: Churn, dtype: int64
Male      3555
Female    3488
Name: customer.gender, dtype: int64
0    5901
1    1142
Name: customer.SeniorCitizen, dtype: int64
No     3641
Yes    3402
Name: customer.Partner, dtype: int64
No     4933
Yes    2110
Name: customer.Dependents, dtype: int64
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: customer.tenure, Length: 73, dtype: int64
Yes    6361
No      682
Name: phone.PhoneService, dtype: int64
No                  3390
Yes                 2971
No phone service     682
Name: phone.MultipleLines, dtype: int64
Fiber optic    3096
DSL            2421
No             1526
Name: internet.InternetService, dtype: int64
No                     3498
Yes                    2019
No internet service    1526
Name: internet.OnlineSecurity, dtype: int64
No                     3088
Yes                    2429
No internet service    1526
Name: internet.OnlineBackup, dtype: int64
No                     3095
Yes                    2422
No internet service    1526
Name: internet.DeviceProtection, dtype: int64
No                     3473
Yes                    2044
No internet service    1526
Name: internet.TechSupport, dtype: int64
No                     2810
Yes                    2707
No internet service    1526
Name: internet.StreamingTV, dtype: int64
No                     2785
Yes                    2732
No internet service    1526
Name: internet.StreamingMovies, dtype: int64
Month-to-month    3875
Two year          1695
One year          1473
Name: account.Contract, dtype: int64
Yes    4171
No     2872
Name: account.PaperlessBilling, dtype: int64
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: account.PaymentMethod, dtype: int64
20.05     61
19.85     45
19.95     44
19.90     44
20.00     43
          ..
116.55     1
106.85     1
68.55      1
108.80     1
67.85      1
Name: account.Charges.Monthly, Length: 1585, dtype: int64
20.20      11
19.75       9
19.90       8
19.65       8
20.05       8
           ..
2387.75     1
6302.80     1
2058.50     1
829.55      1
3707.60     1
Name: account.Charges.Total, Length: 6534, dtype: int64

In [ ]:
colunas1 = ['Churn', 'customer.Partner', 'customer.Dependents', 'phone.PhoneService', 'account.PaperlessBilling']
for coluna in colunas1:
  df[coluna] = df[coluna].map({'No' : 0, 'Yes' : 1})

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
df

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,0,Female,0,1,1,9,1,No,DSL,...,Yes,No,Yes,Yes,No,One year,1,Mailed check,65.60,593.30
1,0003-MKNFE,0,Male,0,0,0,9,1,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,0,Mailed check,59.90,542.40
2,0004-TLHLJ,1,Male,0,0,0,4,1,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,1,Electronic check,73.90,280.85
3,0011-IGKFF,1,Male,1,1,0,13,1,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,1,Electronic check,98.00,1237.85
4,0013-EXCHZ,1,Female,1,1,0,3,1,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,1,Mailed check,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,0,Female,0,0,0,13,1,No,DSL,...,No,No,Yes,No,No,One year,0,Mailed check,55.15,742.90
7263,9992-RRAMN,1,Male,0,1,0,22,1,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,1,Electronic check,85.10,1873.70
7264,9992-UJOEL,0,Male,0,0,0,2,1,No,DSL,...,Yes,No,No,No,No,Month-to-month,1,Mailed check,50.30,92.75
7265,9993-LHIEB,0,Male,0,1,1,67,1,No,DSL,...,No,Yes,Yes,No,Yes,Two year,0,Mailed check,67.85,4627.65
7266,9995-HOTOH,0,Male,0,1,1,63,0,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,0,Electronic check,59.00,3707.60

A coluna "account.Contract" vamos considerar como valores ordinais, variando entre 0, 1 ou 2 anos:

In [ ]:
df['account.Contract'] = df['account.Contract'].map({'Month-to-month' : 0, 'One year' : 1, 'Two year' : 2})
df.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,0,Female,0,1,1,9,1,No,DSL,...,Yes,No,Yes,Yes,No,1,1,Mailed check,65.6,593.30
1,0003-MKNFE,0,Male,0,0,0,9,1,Yes,DSL,...,No,No,No,No,Yes,0,0,Mailed check,59.9,542.40
2,0004-TLHLJ,1,Male,0,0,0,4,1,No,Fiber optic,...,No,Yes,No,No,No,0,1,Electronic check,73.9,280.85
3,0011-IGKFF,1,Male,1,1,0,13,1,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,0,1,Electronic check,98.0,1237.85
4,0013-EXCHZ,1,Female,1,1,0,3,1,No,Fiber optic,...,No,No,Yes,Yes,No,0,1,Mailed check,83.9,267.40

E no restante das colunas, vamos representar as respostas em formato binário, utilizando a função **get_dummies** do Pandas. Optou-se por usar esta função do Pandas ao invés de utilizar a função **OneHotEncoder** da biblioteca Sklearn, pois gostaríamos de manter o formato DataFrame do dados e trabalhar com os nomes das colunas, de forma que seja possível analisar as variáveis de forma visual e possíveis relações entre elas . Desta forma, poderemos gerar tirar *insights* antes de criar o modelo de ML.

In [ ]:
colunas2 = ['customer.gender', 
            'phone.MultipleLines', 
            'internet.InternetService', 
            'internet.OnlineSecurity', 
            'internet.OnlineBackup', 
            'internet.DeviceProtection', 
            'internet.TechSupport', 
            'internet.StreamingTV', 
            'internet.StreamingMovies',  
            'account.PaymentMethod'
            ]
for coluna in colunas2:
  transforma = pd.get_dummies(df[coluna], prefix = coluna)
  df= pd.concat([df, transforma], axis=1).drop([coluna], axis=1)

In [ ]:
df.head()

,customerID,Churn,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,account.Contract,account.PaperlessBilling,account.Charges.Monthly,...,internet.StreamingTV_No,internet.StreamingTV_No internet service,internet.StreamingTV_Yes,internet.StreamingMovies_No,internet.StreamingMovies_No internet service,internet.StreamingMovies_Yes,account.PaymentMethod_Bank transfer (automatic),account.PaymentMethod_Credit card (automatic),account.PaymentMethod_Electronic check,account.PaymentMethod_Mailed check
0,0002-ORFBO,0,0,1,1,9,1,1,1,65.6,...,0,0,1,1,0,0,0,0,0,1
1,0003-MKNFE,0,0,0,0,9,1,0,0,59.9,...,1,0,0,0,0,1,0,0,0,1
2,0004-TLHLJ,1,0,0,0,4,1,0,1,73.9,...,1,0,0,1,0,0,0,0,1,0
3,0011-IGKFF,1,1,1,0,13,1,0,1,98.0,...,0,0,1,0,0,1,0,0,1,0
4,0013-EXCHZ,1,1,1,0,3,1,0,1,83.9,...,0,0,1,1,0,0,0,0,0,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7266
Data columns (total 41 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   customerID                                       7043 non-null   object
 1   Churn                                            7043 non-null   int64
 2   customer.SeniorCitizen                           7043 non-null   int64
 3   customer.Partner                                 7043 non-null   int64
 4   customer.Dependents                              7043 non-null   int64
 5   customer.tenure                                  7043 non-null   int64
 6   phone.PhoneService                               7043 non-null   int64
 7   account.Contract                                 7043 non-null   int64
 8   account.PaperlessBilling                         7043 non-null   int64
 9   account.Charges.Monthly                          7043 non-null   float64
 10  account.Charges.Total                            7043 non-null   float64
 11  customer.gender_Female                           7043 non-null   uint8
 12  customer.gender_Male                             7043 non-null   uint8
 13  phone.MultipleLines_No                           7043 non-null   uint8
 14  phone.MultipleLines_No phone service             7043 non-null   uint8
 15  phone.MultipleLines_Yes                          7043 non-null   uint8
 16  internet.InternetService_DSL                     7043 non-null   uint8
 17  internet.InternetService_Fiber optic             7043 non-null   uint8
 18  internet.InternetService_No                      7043 non-null   uint8
 19  internet.OnlineSecurity_No                       7043 non-null   uint8
 20  internet.OnlineSecurity_No internet service      7043 non-null   uint8
 21  internet.OnlineSecurity_Yes                      7043 non-null   uint8
 22  internet.OnlineBackup_No                         7043 non-null   uint8
 23  internet.OnlineBackup_No internet service        7043 non-null   uint8
 24  internet.OnlineBackup_Yes                        7043 non-null   uint8
 25  internet.DeviceProtection_No                     7043 non-null   uint8
 26  internet.DeviceProtection_No internet service    7043 non-null   uint8
 27  internet.DeviceProtection_Yes                    7043 non-null   uint8
 28  internet.TechSupport_No                          7043 non-null   uint8
 29  internet.TechSupport_No internet service         7043 non-null   uint8
 30  internet.TechSupport_Yes                         7043 non-null   uint8
 31  internet.StreamingTV_No                          7043 non-null   uint8
 32  internet.StreamingTV_No internet service         7043 non-null   uint8
 33  internet.StreamingTV_Yes                         7043 non-null   uint8
 34  internet.StreamingMovies_No                      7043 non-null   uint8
 35  internet.StreamingMovies_No internet service     7043 non-null   uint8
 36  internet.StreamingMovies_Yes                     7043 non-null   uint8
 37  account.PaymentMethod_Bank transfer (automatic)  7043 non-null   uint8
 38  account.PaymentMethod_Credit card (automatic)    7043 non-null   uint8
 39  account.PaymentMethod_Electronic check           7043 non-null   uint8
 40  account.PaymentMethod_Mailed check               7043 non-null   uint8
dtypes: float64(2), int64(8), object(1), uint8(30)
memory usage: 866.6+ KB

Todas as colunas que representam informações referentes a "No phone service" e "No internet service" são redundantes, pois essa informação já está sendo representada nas colunas "phone.PhoneService" e "internet.InternetService_No", respectivamente. Abaixo temos um exemplo de como as duas colunas são perfeitamente opostas.

In [ ]:
redundancia = [df['phone.PhoneService'], df['phone.MultipleLines_No phone service']]
pd.DataFrame(redundancia)

,0,1,2,3,4,5,6,7,8,9,...,7257,7258,7259,7260,7261,7262,7263,7264,7265,7266
phone.PhoneService,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
phone.MultipleLines_No phone service,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

O mesmo ocorre para as colunas com "Yes" e "No" de um mesmo serviço, são perfeitamente opostas e portanto, com informações redundantes. Segue o exemplo:

In [ ]:
redundancia2 = [df['internet.OnlineSecurity_Yes'], df['internet.OnlineSecurity_No']]
pd.DataFrame(redundancia)

,0,1,2,3,4,5,6,7,8,9,...,7257,7258,7259,7260,7261,7262,7263,7264,7265,7266
phone.PhoneService,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
phone.MultipleLines_No phone service,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

Portanto, para deixar nosso dados mais leves, todas estas colunas com informações redundantes serão exluídas.

In [ ]:
df = df.drop(['phone.MultipleLines_No phone service',
              'phone.MultipleLines_No',
              'internet.OnlineSecurity_No internet service',
              'internet.OnlineBackup_No internet service',
              'internet.DeviceProtection_No internet service',
              'internet.TechSupport_No internet service',
              'internet.StreamingTV_No internet service',
              'internet.StreamingMovies_No internet service',
              'internet.OnlineSecurity_No',
              'internet.OnlineBackup_No',
              'internet.DeviceProtection_No',
              'internet.TechSupport_No',
              'internet.StreamingTV_No',
              'internet.StreamingMovies_No'
              ], axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7266
Data columns (total 27 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   customerID                                       7043 non-null   object
 1   Churn                                            7043 non-null   int64
 2   customer.SeniorCitizen                           7043 non-null   int64
 3   customer.Partner                                 7043 non-null   int64
 4   customer.Dependents                              7043 non-null   int64
 5   customer.tenure                                  7043 non-null   int64
 6   phone.PhoneService                               7043 non-null   int64
 7   account.Contract                                 7043 non-null   int64
 8   account.PaperlessBilling                         7043 non-null   int64
 9   account.Charges.Monthly                          7043 non-null   float64
 10  account.Charges.Total                            7043 non-null   float64
 11  customer.gender_Female                           7043 non-null   uint8
 12  customer.gender_Male                             7043 non-null   uint8
 13  phone.MultipleLines_Yes                          7043 non-null   uint8
 14  internet.InternetService_DSL                     7043 non-null   uint8
 15  internet.InternetService_Fiber optic             7043 non-null   uint8
 16  internet.InternetService_No                      7043 non-null   uint8
 17  internet.OnlineSecurity_Yes                      7043 non-null   uint8
 18  internet.OnlineBackup_Yes                        7043 non-null   uint8
 19  internet.DeviceProtection_Yes                    7043 non-null   uint8
 20  internet.TechSupport_Yes                         7043 non-null   uint8
 21  internet.StreamingTV_Yes                         7043 non-null   uint8
 22  internet.StreamingMovies_Yes                     7043 non-null   uint8
 23  account.PaymentMethod_Bank transfer (automatic)  7043 non-null   uint8
 24  account.PaymentMethod_Credit card (automatic)    7043 non-null   uint8
 25  account.PaymentMethod_Electronic check           7043 non-null   uint8
 26  account.PaymentMethod_Mailed check               7043 non-null   uint8
dtypes: float64(2), int64(8), object(1), uint8(16)
memory usage: 1.0+ MB

Desta forma, foi possível reduzir nossos dados de 40 para 26 colunas, sem perda de informação.

## Traduzindo o nome das colunas
Considerando que podem haver pessoas na equipe que não dominam o idioma Inglês, as colunas serão renomeadas e traduzidas para incluir todos os participantes do time.

In [ ]:
renomear = {'customerID' : 'ID',
            'Churn': 'Evasao',
            'customer.SeniorCitizen': 'Idoso',
            'customer.Partner' : 'Parceiro',
            'customer.Dependents' : 'Dependentes',
            'customer.tenure' : 'Meses_Contrato',
            'phone.PhoneService' : 'Servico_Telefone',
            'account.Contract' : 'Tipo_Contrato',
            'account.PaperlessBilling' : 'Fatura_Digital',
            'account.Charges.Monthly' : 'Valor_Mensal',
            'account.Charges.Total' : 'Valor_Total',
            'customer.gender_Female': 'Gen_Feminino',
            'customer.gender_Male' : 'Gen_Masculino',
            'phone.MultipleLines_Yes' : 'Multiplas_Linhas',
            'internet.InternetService_DSL' : 'Internet_DSL',
            'internet.InternetService_Fiber optic': 'Internet_FibraOtica',
            'internet.InternetService_No' : 'Sem_Servico_Internet',
            'internet.OnlineSecurity_Yes' : 'Seguranca_Online',
            'internet.OnlineBackup_Yes' : 'Backup_Online',
            'internet.DeviceProtection_Yes': 'Protecao_Dispositivo',
            'internet.TechSupport_Yes' : 'Suporte_Tecnico_Internet',
            'internet.StreamingTV_Yes' : 'TV_Cabo',
            'internet.StreamingMovies_Yes' : 'Streaming_Filmes',
            'account.PaymentMethod_Bank transfer (automatic)' : 'Transferencia_Bancaria',
            'account.PaymentMethod_Credit card (automatic)' : 'Cartao_Credito',
            'account.PaymentMethod_Electronic check' : 'Cheque_Eletronico',
            'account.PaymentMethod_Mailed check' : 'Cheque'
            }
df.rename(columns = renomear, inplace = True)

In [ ]:
df

,ID,Cliente_Saiu,Idoso,Parceiro,Dependentes,Meses_Contrato,Servico_Telefone,Tipo_Contrato,Fatura_Digital,Valor_Mensal,...,Seguranca_Online,Backup_Online,Protecao_Dispositivo,Suporte_Tecnico_Internet,TV_Cabo,Streaming_Filmes,Transferencia_Bancaria,Cartao_Credito,Cheque_Eletronico,Cheque
0,0002-ORFBO,0,0,1,1,9,1,1,1,65.60,...,0,1,0,1,1,0,0,0,0,1
1,0003-MKNFE,0,0,0,0,9,1,0,0,59.90,...,0,0,0,0,0,1,0,0,0,1
2,0004-TLHLJ,1,0,0,0,4,1,0,1,73.90,...,0,0,1,0,0,0,0,0,1,0
3,0011-IGKFF,1,1,1,0,13,1,0,1,98.00,...,0,1,1,0,1,1,0,0,1,0
4,0013-EXCHZ,1,1,1,0,3,1,0,1,83.90,...,0,0,0,1,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,0,0,0,0,13,1,1,0,55.15,...,1,0,0,1,0,0,0,0,0,1
7263,9992-RRAMN,1,0,1,0,22,1,0,1,85.10,...,0,0,0,0,0,1,0,0,1,0
7264,9992-UJOEL,0,0,0,0,2,1,0,1,50.30,...,0,1,0,0,0,0,0,0,0,1
7265,9993-LHIEB,0,0,1,1,67,1,2,0,67.85,...,1,0,1,1,0,1,0,0,0,1
7266,9995-HOTOH,0,0,1,1,63,0,2,0,59.00,...,1,1,1,0,1,1,0,0,1,0

## Salvando o arquivo
O ultimo passo é salvar o arquivo tratado no formato CSV

In [ ]:
df.to_csv(".../Dados/01-Telco-Customer-Churn-dados-limpos.csv", index = False)